name: wakareeru
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - httpx
  - requests
  - python-dotenv
  - tqdm
  - gradio
  - scikit-learn
  - joblib
  - pip:
      - accelerate
      - huggingface-hub
      - openai
      - torch
      - torchvision
      - transformers
      - pyyaml
